config/routes.rb
SampleApp2::Application.routes.draw do

  get "houses/research"

  resources :microposts

  resources :users
  resources :sessions, only: [:new,:create, :destroy]

  root to: 'static_pages#home'

  match '/signup', to: 'users#new'
  match '/signin', to: 'sessions#new'
  match '/signout', to: 'sessions#destroy'

  match '/help', to: 'static_pages#help'

  match '/about', to: 'static_pages#about'

  match '/home', to: 'static_pages#home'

  match '/data', to: 'houses#data'
  match '/pageData', to: 'houses#pageData'
  match '/pageLayout', to: 'houses#pageLayout'
  match '/research', to: 'houses#research'
  match '/QT', to: 'houses#QT'

end

app/models/house.rb
class House < ActiveRecord::Base
end

app/models/micropost.rb
class Micropost < ActiveRecord::Base
  attr_accessible :content
  belongs_to :user

  validates :user_id, presence: true

  default_scope order: 'microposts.created_at DESC'
end

app/models/user.rb
class User < ActiveRecord::Base
attr_accessible(:name, :email, :password, :password_confirmation)
has_secure_password
has_many :microposts, dependent: :destroy

validates(:name,presence: true, length: {maximum: 10})
validates :email, presence: true
validates :password, length: {minimum: 6}
validates :password_confirmation, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/houses_controller.rb
class HousesController < ApplicationController
  
 
  def research
	#render 'research', :layout => true
  end

  def data
	#render :file=>'c:/sites/rails_projects/sample_app2/app/views/houses/08Data', :content_type=>'application/xml', :format => [:xml],:layout => false
    #logger.warn params[:house]
	render '08Data', :format => [:xml], :layout => false
  end

  def pageData
    logger.debug "Params start"
    logger.debug request.post?

	postData = params[:Data].gsub("&lt;", "<")
	postData.gsub!("&gt;",">")

    #logger.debug postData

	hash = Hash.from_xml(postData)
	
	pageLength = 25

	pos = hash["Grid"]["Body"]["B"]["Pos"]

	logger.debug "Pos=" 
    logger.debug pos
    
	logger.debug "Params end"

	#render :file=>"08Page.xml", :content_type=>'application/xml'

	num = pos.to_i()
	startP = num*pageLength
	endP = (num+1)*pageLength
	#housePage = House.where("id > #{startP} AND id <= #{endP}")
	#housePage = House.find_by_id("1")
	
	housePage = House.select("mls,pin,city,subdiv,stat,strnum,cp,strname,sfx,rprnp,lpsp,rooms,beds,fullbaths,halfbaths,typ,sci,garages,info,asf,yearbuilt,dues,bsmt,bsmtdesc,closeddate,contractdate,fin,hsdist,hsname,listdate,listprice,lmt,origlistprice,shortsale,taxexempt,taxyear,taxes,baths,origrent,rd,rnp,rp").where("id > #{startP} AND id <= #{endP}")

	xml = "<Grid><Par><P Name=\"P\" List=\"Count,Expanded,mls,pin,c,sd,stat,strn,cp,strnam,sfx,rnp2,lsp,rm,bed,fbth,hbth,typ,sci,grg,info,asf,yrblt,due,bsmt,bsmtinf,clsdt,ctrtdt,fin,hsd,hsn,lstdt,lstpr,lmt,olstpr,ss,emp,taxyr,tax,bth,ornt,rd,rnp,rp\"/></Par><Body><B>"
	xml2 = ""
	housePage.each do |house|
	    xml2 << "<I>|P|0|0"
		house.attributes.each do |attr|
			xml2 << "|"
			xml2 << attr[1].to_s()
		end
		xml2 << "</I>"
	end
	xml << xml2
	xml << "/B></Body></Grid>"
	logger.debug xml
	render :text => xml, :format => [:xml], :layout => false

	#render '08Page', :format => [:xml], :layout => false
  end

  def pageLayout
    #logger.warn params
	#render :file=>"08layout.xml", :content_type=>'application/xml'
	render '08Layout', :format => [:xml], :layout => false
  end

  def QT
	#housePage = House.select("mls,strnum,cp,strname,sfx,rprnp,lpsp,listprice,lmt,origlistprice,origrent,rd,rnp,rp").where("mls =#{params[:row]}")

	#logger.debug params[:sd].empty?
	#logger.debug params[:c]

	@subdiv = params[:sd]
	#@city = params[:c]
	#@rnp = params[:rp]
	#@lsp= params[:lsp]
	@subjectHouse = House.select("mls,strnum,cp,strname,sfx,city,rprnp,lpsp,listprice,lmt,origlistprice,origrent,rd,rnp,rp").where("mls='#{params[:mls]}'").first

    @house = {}
	if params[:sd].empty? and params[:c].empty?
	elsif params[:sd].empty?
		@house = House.select("mls,strnum,cp,strname,sfx,city,rprnp,lpsp,listprice,lmt,origlistprice,origrent,rd,rnp,rp").where("city='#{params[:c]}'")
	else
		@house = House.select("mls,strnum,cp,strname,sfx,city,rprnp,lpsp,listprice,lmt,origlistprice,origrent,rd,rnp,rp").where("subdiv='#{params[:sd]}'")
	end
	logger.debug "Subject property"
	logger.debug @subjectHouse.strname
	
	logger.debug "similar property"
	logger.debug @house.first.rprnp

	render 'QuickTake'
  end

end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
before_filter :signed_in_user, only: [:create, :destroy]
  # GET /microposts
  # GET /microposts.json
  def index
    @microposts = Micropost.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @microposts }
    end
  end

  # GET /microposts/1
  # GET /microposts/1.json
  def show
    @micropost = Micropost.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @micropost }
    end
  end

  # GET /microposts/new
  # GET /microposts/new.json
  def new
    @micropost = Micropost.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @micropost }
    end
  end

  # GET /microposts/1/edit
  def edit
    @micropost = Micropost.find(params[:id])
  end

  # POST /microposts
  # POST /microposts.json
  def create
    @micropost = Micropost.new(params[:micropost])

    respond_to do |format|
      if @micropost.save
        format.html { redirect_to @micropost, notice: 'Micropost was successfully created.' }
        format.json { render json: @micropost, status: :created, location: @micropost }
      else
        format.html { render action: "new" }
        format.json { render json: @micropost.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /microposts/1
  # PUT /microposts/1.json
  def update
    @micropost = Micropost.find(params[:id])

    respond_to do |format|
      if @micropost.update_attributes(params[:micropost])
        format.html { redirect_to @micropost, notice: 'Micropost was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @micropost.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /microposts/1
  # DELETE /microposts/1.json
  def destroy
    @micropost = Micropost.find(params[:id])
    @micropost.destroy

    respond_to do |format|
      format.html { redirect_to microposts_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

def new
end

def create
end

def destroy
end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_filter :signed_in_user, only: [:edit, :update]

  def edit
	@user = User.find(params[:id])
  end

  def update
	@user = User.finf(params[:id])
	if @user.update_attributes(params[:user])
		flash[:success] = "Profile updated"
		sign_in @user
		redirect_to @user
	#else
		#render 'edit'
	end
  end


  def show
    @user=User.find(params[:id])
	@microposts = @user.microposts.paginate(page: params[:page])
  end

  def new
    @user = User.new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/houses_helper.rb
module HousesHelper
end

app/helpers/microposts_helper.rb
module MicropostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

    def sign_in(user)
		current_user = user
	end

	def current_user=(user)
		@current_user = user
	end

	def current_user
	end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper

	def gravatar_for(user)
		gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
		gravatar_url = "http://gravatar.com/avatar/#{gravatar_id}.png"
		image_tag(gravatar_url, alt: user.name, class: "gravatar")
	end
end

app/views/houses/08Data.html.erb
<Grid>
   <Body>@@@30</Body>
</Grid>

app/views/houses/08Layout.html.erb
<Grid>
   <Cfg id="ASP" SuppressCfg="1"/>
   <!--<Cfg MainCol="id"/>-->
   <Cfg Paging="3" PageLength="25" MaxPages="2"/>
   <Cfg PageLengthDiv="50" FastPages="500"/>
   <Cfg ChildPaging="3" RemoveCollapsed="2"/>
   <Cfg ChildParts="2" ChildPartLength="25" ChildPartMin="0" MaxChildParts="4"/>
   <Cfg ColPaging="2" ColPageLength="10" ColPageMin="0" MaxColPages="2"/>
   <Cfg Style="Office"/>
  <Cfg MenuColumnsCount="10"/>
   <Pager Width="80" Visible="0"/>
   <Panel Visible="0"/>
   <Def>
      <!--<D Name="c" Count="20" Expanded="0"/>-->
      <!--<D Name="C" Width="40" Prepared="1" CanSort="0" Type="Int"/>-->
   </Def>
  <!--
   <Solid>
      <I id="PAGER" Cells="LIST" Space="4" Height="46"
         LISTType="Pages" LISTRelWidth="1" LISTCount="10" LISTStep="10,50,100,500,1000" LISTWrap="1" LISTAlign="center"
         />
   </Solid>
   <Solid>
      <I id="INFO" Cells="PAGER,INFO" Space="4" Calculated="1"
         PAGERType="Pager" PagerEditWidth="70"
         INFOType="Html" INFORelWidth="1" INFOAlign="Right"
         INFOFormula="'Columns:&lt;b>1,000&lt;/b>&amp;nbsp; Root rows: &lt;b>'+NumberToString(count(),',0')+'&lt;/b>&amp;nbsp; Child rows: &lt;b>N/A&lt;/b>&amp;nbsp; Loaded rows: &lt;b>'+Grid.LoadedCount+'&lt;/b>&amp;nbsp; Rendered rows: &lt;b>'+Grid.RowCount+'&lt;/b>'"
         /> 
   </Solid>
   <Toolbar
      Cells="Reload,Add,AddChild,ExpandAll,CollapseAll,Columns,Cfg,StyleTitle,StyleCombo,Empty,SHOW"
      Styles="2"
      SHOWType="Bool" SHOWLabel="Show right pager" SHOWFormula="Grid.Pager.Visible" SHOWCanEdit="1"
      SHOWOnChange="Grid.Pager.Visible = Value; Grid.Rerender();" SHOWCanFocus="0"
      />
      -->

  <Toolbar
     Cells="StyleTitle,StyleCombo"
     Styles="2"
     SHOWCanEdit="1"
     SHOWOnChange="Grid.Pager.Visible = Value; Grid.Rerender();" SHOWCanFocus="0"/>

  <Header mls="MLS" pin="PIN" c="City" sd="Sub Division" stat="Status" strn="Street #" cp="CP" strnam="Street Name" sfx="Suffix" rnp2="RP/RNP" lsp="LP/SP" rm="Rooms" bed="All Beds" fbth="Full Baths" hbth="Half Baths" typ="Type DE/AT" 
           sci="SCI" grg="Garages" inf="Additional Info" yrblt="Year Built" asf="ASF" yrblt="Year Built" 
           Due="Association Dues" bsmt="Basement" bsmtinf="Basement Description" clsdt="Closed Date" ctrtdt="Contract Date" hsd="High School District" hsn="High School Name" lstdt="List Date" lstpr="List Price" olstpr="Original List Price" ss="Short Sale"
           exp="Tax Exempt" taxyr="Tax Year" tax="Taxes" bth="Baths" ornt="Original Rent" rd="RD" rnp="RNP" rp="RP"/>
   <LeftCols>
     <C Name="mls" Type="Text" Width="70" CanEdit="0" CanSort="1"/>
     <C Name="pin" Type="Text" Width="80" CanEdit="0" CanSort="0"/>
   </LeftCols>
   <Cols>
     <C Name="c"/>
     <C Name="sd"/>
     <C Name="stat"/> <C Name="strn"/> <C Name="cp"/> <C Name="strnam"/> <C Name="sfx"/> <C Name="rnp2"/> <C Name="lsp"/> <C Name="rm"/> <C Name="bed"/> <C Name="fbth"/>
      <C Name="hbth"/> <C Name="typ"/> <C Name="sci"/> <C Name="grg"/> <C Name="inf"/> <C Name="asf"/> <C Name="yrblt"/> <C Name="due"/> <C Name="bsmt"/> <C Name="bsmtinf"/>
      <C Name="clsdt"/> <C Name="ctrtdt"/> <C Name="fin"/> <C Name="hsd"/> <C Name="hsn"/> <C Name="lstdt"/> <C Name="lstpr"/> <C Name="lmt"/> <C Name="olstpr"/>
      <C Name="ss"/> <C Name="exp"/> <C Name="taxyr"/> <C Name="tax"/> <C Name="bth"/> <C Name="ornt"/> <C Name="rd"/> <C Name="rnp"/><C Name="rp"/>    
   </Cols>
</Grid>

app/views/houses/08Page.html.erb
<Grid>
   <Par>
      <P Name="P" List="Count,Expanded,mls,pin,c,sd,stat,strn,cp,strnam,sfx,rnp2,lsp,rm,bed,fbth,hbth,typ,sci,grg,info,asf,yrblt,due,bsmt,bsmtinf,clsdt,ctrtdt,fin,hsd,hsn,lstdt,lstpr,lmt,olstpr,ss,emp,taxyr,tax,bth,ornt,rd,rnp,rp"/>
   </Par>
  <Body>
      <B>
        <I>|P|0|0|07998081||Oswego|CHURCHILL CLUB|ACTV|250|CP|Bluegrass|PKWY|1200||9|3|2|1|2 Stories|Short Sale|2|Short Sale  Pre-Foreclosure|2290|2005||Full|Unfinished||||308|OSWEGO HIGH SCHOOL|2/17/2012||13||||||2.1||||1200</I>
        <I>|P|0|0|08006269||Oswego||NEW|64|E|Benton||1295||5|3|1|0|1 Story|Short Sale|1|Short Sale  Pre-Foreclosure|1120|||Full|Unfinished||||308||2/29/2012||1||||||1||||1200</I>
        <I>|P|0|0|08004547||Oswego|BLACKBERRY KNOLL|NEW|473||Grape Vine|TRL|1500||8|4|2|1|2 Stories|Variable|2|Pre-Foreclosure|2100|2004||Full|Unfinished||||308|OSWEGO HIGH SCHOOL|2/27/2012||3||||||2.1||||1500</I>
        <I>|P|0|0|07956224||Oswego|BLACKBERRY KNOLL|ACTV|495||GRAPE VINE|TRL|1550||6|3|2|1|2 Stories|None|2|None|1750|2004||Full|Unfinished||||308|OSWEGO HIGH SCHOOL|12/6/2011||86||||||2.1||||1550</I>
        <I>|P|0|0|07964028||Oswego||TEMP|7|E|ANCHOR|DR|1595||8|3+1 bsmt|3|0|Split Level w/ Sub|None|2|None|1600|||Partial|Sub-Basement||||308|OSWEGO HIGH SCHOOL|12/23/2011||69||||||3||||1595</I>
        <I>|P|0|0|07909393||Oswego|Heritage of Oswego|ACTV|618||Salem|CIR|1800||10|4|2|1|2 Stories|None|3.5||0|1995||Partial|Finished  Crawl||||308|OSWEGO EAST HIGH SCHOOL|9/22/2011||161||||||2.1||||1800</I>
        <I>|P|0|0|07995939||Oswego|Farmington Lakes|ACTV|371||Kensington|DR|1995||8|3|2|1|2 Stories|None|2|None|1744|2003||Full  English|Other||||308||2/14/2012||16||||||2.1||||1995</I>
        <I>|P|0|0|08004246||Oswego|CHURCHILL CLUB|NEW|611||Paris|AVE|2000||9|4|2|1|2 Stories|None|2|None|2541|2005||Full|Unfinished||||308|OSWEGO HIGH SCHOOL|2/26/2012||4||||||2.1||||2000</I>
        <I>|P|0|0|07948033||Oswego|CHURCHILL CLUB|ACTV|207||BLUEGRASS|PKWY|2100||10|4|2|1|2 Stories|None|3|None|2754|2007||Full|Unfinished||||308|OSWEGO EAST HIGH SCHOOL|11/20/2011||102||||||2.1||||2100</I>
        <I>|P|0|0|07999033||Oswego|Prescott Mill|ACTV|105||Chapin|WAY|2100||8|4|2|1|2 Stories|None|2|None|2289|2010||Full|Unfinished  Bathroom Rough-In||||308|OSWEGO EAST HIGH SCHOOL|2/18/2012||12||||||2.1||||2100</I>
        <I>|P|0|0|07987371||Oswego|NA-AU-SAY WOODS|ACTV|8||Iroquois|CT|2250||8|3|3|0|1 Story|None|3|None|2008|1998||Full  English|Partially Finished  Exterior Access||||308|OSWEGO HIGH SCHOOL|2/1/2012||29||||||3||||2250</I>
        <I>|P|0|0|07902863||Oswego|DEERPATH CREEK|ACTV|342||Prairieview|DR|2295||9|4|3|0|2 Stories|None|3||3000|2003||Full|Unfinished||||308|OSWEGO HIGH SCHOOL|9/14/2011||169||||||3||||2295</I>
        <I>|P|0|0|07986534||Oswego|DEERPATH CREEK|CTGO|412||SUDBURY|CIR|2395||12|4+1 bsmt|3|1|2 Stories|None|3||3200|2004||Full|Finished||2/10/2012||308|OSWEGO HIGH SCHOOL|2/1/2012||29||||||3.1||||2395</I>
        <I>|P|0|0|07812314||Oswego|GATES CREEK WEST|ACTV|503||MEADOWWOOD|LN|2695||10|4|4|0|2 Stories|None|3|None|4371|2004||Full  English|Unfinished||||115|YORKVILLE HIGH SCHOOL|5/20/2011||286||||||4||||2695</I>
        <I>|P|0|0|07889543|0317102011|Oswego||SS|2245||STATE ROUTE 31|RD||55000|7|3|2|0|1 Story|Short Sale|2|Short Sale|1230|1940|0|None|None||12/19/2011||308||8/26/2011|55000|188|99900||Homeowner|2009|5352|2||||</I>
        <I>|P|0|0|07967926|0319229008|Oswego||TEMP|24||FULLER|AVE||80000|6|4|1|0|2 Stories|Short Sale|2|Short Sale|1200|1950|0|Full|Unfinished||||308|OSWEGO HIGH SCHOOL|1/4/2012|80000|57|104900||Homeowner|2010|4012.54|1||||</I>
        <I>|P|0|0|07814770|0318260019|Oswego||TEMP|120||Presidential|BLVD||84900|7|2|2|1|2 Stories|Short Sale  Variable|2|Short Sale|0|2004|120|None|Slab||||308||5/21/2011|84900|285|129900||Homeowner|2009|"3|964"|2.1||||</I>
        <I>|P|0|0|07976643|0317152004|Oswego||ACTV|2408-A||RT 31|||99900|8|4|2|0|2 Stories|Short Sale|2|Short Sale|2430|1933|0|Full|Partially Finished||||308||1/17/2012|99900|44|129900|||2009|5850|2||||</I>
        <I>|P|0|0|07520845|0302471012|Oswego||SS|74||WINGATE|DR||101500|7|3|1|1|2 Stories|Short Sale|2|Short Sale|0|1997|55|Full|Partially Finished||1/27/2012||308||5/5/2010|101500|666|199900||Homeowner|2010|3948.5|1.1||||</I>
        <I>|P|0|0|07939049|0307440160|Oswego|FOX CHASE OF OSWEGO|CTGO|261||Fox Chase|DR||110000|8|3|2|1|2 Stories|Short Sale|2|REO/Lender Owned  Short Sale|1700|1995|0|Full|Unfinished||2/23/2012||308||11/5/2011|110000|117|175000||None|2010|5281|2.1||||</I>
      </B>
   </Body>
</Grid>

app/views/houses/Backup/08Data.html - Copy.erb
<Grid>
   <Body>@@@10000</Body>
</Grid>

app/views/layouts/_footer.html.erb
<footer class="footer navbar">
  <div class="navbar-inner">
    <small>
      <a href="#">Property Research Services</a>
    </small>
    <nav>
      <ul class="nav pull-right">
        <li>
          <%= link_to "About", about_path %>
        </li>
        <li>
          <%= link_to "Contact", '#' %>
        </li>
        <li>
          <a href="#">News</a>
        </li>
      </ul>
    </nav>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top">
  <div class="navbar-inner">
	<div class="container">
		<%= link_to "Property Research Center", '#', id: "logo" %>
		<nav>
			<ul class="nav pull-right">
				<li><%= link_to "Home", root_path %></li>
				<li><%= link_to "Help", help_path %></li>
				<li><%= link_to "Sign in", '#' %></li>
			</ul>
		</nav>
	</div>
  </div>
</header>

app/views/layouts/application.html.erb

<!DOCTYPE html>
<html>
<head>
  <title>Property Research Center | <%=yield(:title)%></title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDffO6cRmxwr74yUs4TC8ctPMvS4lf7G8w&sensor=true" type="text/javascript"></script>
<meta name="viewport" content="initial-scale=1.0, user-scalable=no" />
</head>
<body>
<%= render 'layouts/header' %>
<%= yield %>
<%= render 'layouts/footer' %>
<!--
<%= debug(params) if Rails.env.development? %>
-->
</body>
</html>

app/views/microposts/_form.html.erb
<%= form_for(@micropost) do |f| %>
  <% if @micropost.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@micropost.errors.count, "error") %> prohibited this micropost from being saved:</h2>

      <ul>
      <% @micropost.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/microposts/_micropost.html.erb
<li>
  <span class="content"><%= micropost.content %></span>
  <span class="timestamp">Posted <%= time_ago_in_words(micropost.created_at) %> ago.</span>
</li>

app/views/microposts/edit.html.erb
<h1>Editing micropost</h1>

<%= render 'form' %>

<%= link_to 'Show', @micropost %> |
<%= link_to 'Back', microposts_path %>

app/views/microposts/index.html.erb
<h1>Listing microposts</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @microposts.each do |micropost| %>
  <tr>
    <td><%= link_to 'Show', micropost %></td>
    <td><%= link_to 'Edit', edit_micropost_path(micropost) %></td>
    <td><%= link_to 'Destroy', micropost, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Micropost', new_micropost_path %>

app/views/microposts/new.html.erb
<h1>New micropost</h1>

<%= render 'form' %>

<%= link_to 'Back', microposts_path %>

app/views/microposts/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_micropost_path(@micropost) %> |
<%= link_to 'Back', microposts_path %>

app/views/static_pages/about.html.erb
<%provide(:title,'About us')%>
<h1>About us</h1>
<p>
  The <a href="http://railstutorial.org/help">Rails Tutorial help page</a> is a project to make a book and screencasts to teach web development with
  <a href="http://railstutorial.org/book">Rails Totorial book</a>. This is the sample application for the tutorial.
</p>

app/views/static_pages/help.html.erb
<%provide(:title,'Help')%>

  <h1>Help</h1>
<p>
  Get help on the Ruby on Rails Tutorial at the
  <a href="http://railstutorial.org/help">Rails Tutorial help page</a>.
  To get help on this sample app, see the
  <a href="http://railstutorial.org/book">Rails Totorial book</a>.
</p>

app/views/static_pages/home.html.erb
<%provide(:title,'Home')%>

<div class="center hero-unit">
  <h1>Welcome to the Sample App</h1>
  <h2>
      This is the home page for the
      <a href="http://railstutorial.org/">Ruby on Rails Tutorial</a> sample application
    </h2>

	<%= link_to "Sign up now!", signup_path, class: "btn btn-large btn-primary" %>
</div>

	<%= link_to image_tag("rails.png", alt: "Rails"), 'http://rubyonrails.org/' %>

app/views/users/new.html.erb
<%= provide(:title, 'Sign up') %>
<h1>Sign up</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@user) do |f| %>
      <%= f.label :name %>
      <%= f.text_field :name %>

        <%= f.label :email %>
        <%= f.text_field :email %>

          <%= f.label :password %>
          <%= f.text_field :password %>

            <%= f.label :password_confirmation,  "Confirmation" %>
            <%= f.text_field :password_confirmation %>

            <%= f.submit "Create my account", :class => "btn btn-large btn-primary" %>
      <% end %>
          </div>
</div>
<p>Find me in app/views/users/new.html.erb</p>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
<aside class="span4">
<section>
<h1>
<%= gravatar_for @user %>
<%= @user.name %>
</h1>
</section>
</aside>

<div class="span8">
<% if @user.microposts.any? %>
	<h3>Microposts (<%= @user.microposts.count %>)</h3>
	<ol class="microposts">
		<%= render @microposts %>
	</ol>
	<%= will_paginate @microposts %>
	<% end %>
</div>
</div>